phuocng/frontend-tips

posts/trim-the-spaces-before-parsing-a-number.md
=> Fix incorrect regular expression

posts/style-broken-images.md
=> Use double-colons for pseudo-elements

posts/prevent-a-string-from-being-escaped.md
https://getfrontend.tips/prevent-a-string-from-being-escaped.html
=> Prevent a string from being escaped

_includes/layouts/base.njk, _includes/layouts/post.njk, css/index.css, posts/make-a-table-with-equal-column-widths.md
https://getfrontend.tips/make-a-table-with-equal-column-widths.html
=> Make a table with equal column widths

posts/pretty-format-json.md
=> Fix typo in "posts/pretty-format-json.md"

posts/avoid-to-use-colons-and-periods-in-the-id-attribute.md, posts/do-not-use-submit-to-name-a-submit-button.md
https://getfrontend.tips/do-not-use-submit-to-name-a-submit-button.html
=> Good practice: Do not use submit to name a submit button

posts/add-a-line-break-between-inline-elements.md
https://getfrontend.tips/add-a-line-break-between-inline-elements.html
=> Tip 67: Add a line break between inline elements

css/index.css, posts/log-the-full-object-in-nodejs.md, posts/pretty-format-json.md
https://getfrontend.tips/log-the-full-object-in-nodejs.html
=> Tip 68: Log the full object in NodeJS

posts/pure-collapsible-element.md
https://getfrontend.tips/pure-collapsible-element.html
=> Tip 72: Pure collapsible element

posts/always-put-the-footer-at-the-bottom.md
https://getfrontend.tips/always-put-the-footer-at-the-bottom.html
=> Tip 73: Always put the footer at the bottom

posts/unpack-a-property-of-an-object-with-different-name.md
https://getfrontend.tips/unpack-a-property-of-an-object-with-different-name.html
=> Tip 75: Unpack a property with different name

posts/run-the-last-command-as-the-root-user.md
https://getfrontend.tips/run-the-last-command-as-the-root-user.html
close #4
=> Tip 76: Run the last command as the root user

posts/checkout-the-previous-branch.md
https://getfrontend.tips/checkout-the-previous-branch.html
=> Tip 77: Checkout the previous branch

posts/replace-multiple-if-statements-with-a-lookup-table.md, posts/replace-multiple-if-statements-with-a-single-switch-statement.md
https://getfrontend.tips/replace-multiple-if-statements-with-a-lookup-table.html
=> Good practice 78: Replace multiple if statements with a lookup table

_includes/layouts/base.njk, posts/add-keyboard-shortcuts.md, posts/copy-screenshots-to-the-clipboard-on-macos.md
https://getfrontend.tips/add-keyboard-shortcuts.html
=> Trick 84: Add keyboard shortcuts

posts/number-headings-and-subheadings-automatically.md
https://getfrontend.tips/number-headings-and-subheadings-automatically.html
=> Tip 85: Number headings and subheadings automatically

posts/separate-list-items.md, posts/style-list-items-with-special-characters.md
https://getfrontend.tips/style-list-items-with-special-characters.html
=> Tip 86: Style list items with special characters

posts/accept-any-numbers-of-parameters.md, posts/create-a-function-that-accepts-a-single-parameter.md
https://getfrontend.tips/create-a-function-that-accepts-a-single-parameter.html
=> Tip 87: Create a function that accepts a single parameter

posts/save-a-few-bytes-when-checking-the-existence-of-module.md
https://getfrontend.tips/save-a-few-bytes-when-checking-the-existence-of-module.html
=> Trick 88: Save a few bytes when checking the existence of module

posts/truncate-long-text.md
https://getfrontend.tips/truncate-long-text.html
=> Tip 89: Truncate long text

posts/view-a-file-in-a-different-branch-without-switching-the-branch.md
https://getfrontend.tips/view-a-file-in-a-different-branch-without-switching-the-branch.html
=> Tip 90: View a file in a different branch without switching the branch

posts/shorten-import-paths-in-typescript.md
https://getfrontend.tips/shorten-import-paths-in-typescript.html
=> Tip 93: Shorten import paths in TypeScript

posts/append-leading-zeros-to-ordered-list-items.md, posts/use-negative-nth-child-and-nth-last-child.md
https://getfrontend.tips/append-leading-zeros-to-ordered-list-items.html
=> Tip 94: Append leading zeros to ordered list items

posts/always-use-noopener-or-noreferrer-for-links-opened-in-new-tabs.md, posts/remove-the-border-from-the-last-navigation-item.md
https://getfrontend.tips/always-use-noopener-or-noreferrer-for-links-opened-in-new-tabs.html
=> Practice 95:  Always use noopener or noreferrer for links opened in new tabs

posts/shorten-import-paths-in-typescript.md, posts/shorten-import-paths-in-webpack.md
https://getfrontend.tips/shorten-import-paths-in-webpack.html
=> Tip 97: Shorten import paths in Webpack

posts/open-a-package-s-homepage-or-repo.md
https://getfrontend.tips/open-a-package-s-homepage-or-repo.html
=> Tip 98: Open a package's homepage or repo

posts/center-an-element-vertically-and-horizontally.md
https://getfrontend.tips/center-an-element-vertically-and-horizontally.html
=> Tip 99: Center an element vertically and horizontally

posts/append-leading-zeros-to-ordered-list-items.md, posts/number-headings-and-subheadings-automatically.md, posts/style-index-numbers-of-list-items.md, posts/style-list-items-with-special-characters.md
https://getfrontend.tips/style-index-numbers-of-list-items.html
=> Tip 100: Style index numbers of list items

posts/create-a-file-of-any-size.md
https://getfrontend.tips/create-a-file-of-any-size.html
=> Tip 103: Create a file of any size

posts/early-return.md, posts/replace-multiple-if-statements-with-a-lookup-table.md, posts/replace-multiple-if-statements-with-a-single-switch-statement.md
https://getfrontend.tips/early-return.html
=> Good practice 104: Early return

posts/avoid-using-css-import.md
https://getfrontend.tips/avoid-using-css-import.html
=> Good practice 105: Avoid using CSS @import

posts/load-given-characters-in-a-google-font-request.md
https://getfrontend.tips/load-given-characters-in-a-google-font-request.html
=> Tip 106: Load given characters in a Google font request

posts/prevent-macos-from-going-to-sleep.md
https://getfrontend.tips/prevent-macos-from-going-to-sleep.html
=> Tip 108: Prevent macOS from going to sleep

posts/combine-google-font-requests.md
https://getfrontend.tips/combine-google-font-requests.html
=> Tip 109: Combine Google font requests

.eleventy.js, posts/early-return.md, posts/replace-multiple-if-statements-with-a-lookup-table.md, posts/replace-multiple-if-statements-with-a-single-switch-statement.md, posts/use-array-includes-for-multiple-conditionals.md
https://getfrontend.tips/use-array-includes-for-multiple-conditionals.html
=> Tip 110: Use Array.includes for multiple conditionals

posts/add-an-icon-to-external-links.md, posts/ignore-case-sensitivity-in-a-css-attribute-selector.md
https://getfrontend.tips/ignore-case-sensitivity-in-a-css-attribute-selector.html
=> Tip 111: Ignore case sensitivity in a CSS attribute selector

posts/combine-styles-with-the-is-pseudo-class-selector.md
https://getfrontend.tips/combine-styles-with-the-is-pseudo-class-selector.html
=> Tip 112: Combine styles with the :is pseudo-class selector

posts/create-an-one-time-event-handler.md
https://getfrontend.tips/create-an-one-time-event-handler.html
=> Tip 113: Create an one-time event handler

posts/create-an-one-time-event-handler.md, posts/start-a-simple-web-server-on-macos.md
https://getfrontend.tips/start-a-simple-web-server-on-macos.html
=> Tip 114: Start a simple web server on macOS

posts/smooth-scrolling-with-pure-css.md
https://getfrontend.tips/smooth-scrolling-with-pure-css.html
=> Tip 115: Smooth scrolling with pure CSS

posts/avoid-invisible-text-when-loading-a-font.md, posts/combine-google-font-requests.md, posts/load-given-characters-in-a-google-font-request.md
https://getfrontend.tips/avoid-invisible-text-when-loading-a-font.html
=> Tip 117: Avoid invisible text when loading a font

posts/display-links-in-the-print-mode.md
https://getfrontend.tips/display-links-in-the-print-mode.html
=> Tip 118: Display links in the print mode

posts/add-a-subject-to-a-mailto-link.md
https://getfrontend.tips/add-a-subject-to-a-mailto-link.html
=> Tip 119: Add a subject to a mailto link

posts/prevent-browsers-from-asking-to-translate.md
https://getfrontend.tips/prevent-browsers-from-asking-to-translate.html
=> Tip 123: Prevent browsers from asking to translate

posts/validate-an-input-value-with-the-pattern-attribute.md
https://getfrontend.tips/validate-an-input-value-with-the-pattern-attribute.html
=> Tip 124: Validate an input value with the pattern attribute

posts/log-the-full-object-in-nodejs.md, posts/pretty-format-json.md, posts/transform-values-from-a-json-representation.md
https://getfrontend.tips/transform-values-from-a-json-representation.html
=> Tip 125: Transform values from a JSON representation

posts/create-shapes-with-the-clip-path-property.md
https://getfrontend.tips/create-shapes-with-the-clip-path-property.html
=> Tip 126: Create shapes with the clip path property

posts/create-a-function-that-accepts-a-single-parameter.md
Noticed the link wasn't working, corrected
=> Corrected link to 1 LOC site

posts/move-the-cursor-to-any-position-in-a-macos-command.md
At first, I didn't get that this type related to the terminal, so I've updated the content to make that explicit to hopefully help others in the same position. Whilst there, I corrected the grammar in the content.
=> Made "terminal" explicit, corrected grammar

.eleventy.js, contents/_includes/layouts/base.njk, contents/_includes/layouts/post.njk, contents/feed.njk, contents/index.njk, package.json
=> feat: Add RSS feed

contents/create-an-array-with-conditional-elements.mdx, contents/set-git-configuration-conditionally.mdx, contents/use-multiple-ssh-keys-for-different-github-accounts.mdx
https://phuoc.ng/collection/tips/set-git-configuration-conditionally/
=> feat: Set Git configuration conditionally

contents/include-properties-conditionally.mdx
https://phuoc.ng/collection/tips/include-properties-conditionally/
=> feat: Include properties conditionally

contents/select-the-direct-children-of-an-element.mdx
https://phuoc.ng/collection/tips/select-the-direct-children-of-an-element/
=> feat: Select the direct children of an element

contents/pass-specified-environments-to-webpack.mdx
https://phuoc.ng/collection/tips/pass-specified-environments-to-webpack/
=> feat: Pass specified environments to Webpack

contents/avoid-using-default-exports.mdx
https://phuoc.ng/collection/tips/avoid-using-default-exports/
=> feat: Avoid using default exports

contents/prevent-scrolling-behind-a-fixed-header.mdx
https://phuoc.ng/collection/tips/prevent-scrolling-behind-a-fixed-header/
=> feat: Prevent scrolling behind a fixed header

contents/copy-variables-from-the-browser-console-to-the-clipboard.mdx
https://phuoc.ng/collection/tips/copy-variables-from-the-browser-console-to-the-clipboard/
=> feat: Copy variables from the browser console to the clipboard
